### ISSUE TITLE
Matrix: Read later / Mark as unread

### ISSUE THREAD

**Issue by mordamax** [paritytech/matrix-admin-bot#14]
This is very popular request among matrix users, and IMO it must be a core matrix functionality, rather than custom implementation. Although, i saw issues on matrix repos - like https://github.com/matrix-org/matrix-spec/issues/612 or https://github.com/matrix-org/synapse/issues/5601, or https://github.com/vector-im/element-meta/issues/347 
... Since 2017 🤦 

Question - how can we make it? Either help them or do a workaround or do something more "smart" 😄 
No clear idea how to do this, but this is part of an issue - investigate and propose possible solutions, and implement

**Comment by hnykda** [comment]
@yncyrydybyl can you please point to your source? I can't find it anywhere.

**Comment by mordamax** [comment]
should be fixed with https://schildi.chat/
