### ISSUE TITLE
Matrix: Augment user profile with Parity information

### ISSUE THREAD

**Issue by mordamax** [paritytech/matrix-admin-bot#15]
> User profile: where they are, how they like working, response time, profile photo (cross platform), how to work with them, timezone, handles of Twitter and GitHub

**Problem**
When you open someone's profile in Element - often it's hard to connect the dots with github, bamboo and/or find the right person. 

**Solution**
How exactly this should be done, needs to be investigated. But ideally that could be added in sidebar, which opens when you click on user image, as its own block, with the information loaded from BambooHR
<img width="439" alt="image" src="https://user-images.githubusercontent.com/1177472/171513858-c088f7a9-f26b-4c6b-9173-3e46eefd903a.png">

**Comment by yncyrydybyl** [comment]
I would suggest to make a widget for this. The widget should get data from the room about the users in there and show the most recent one.

There are some examples to look at for the widget logic:

- https://github.com/toger5/Team_summary_widget
- https://github.com/toger5/st-petersburg-widget
- https://github.com/Half-Shot/matrix-spanner-widget/tree/main/src

**Comment by yncyrydybyl** [comment]
We need to find out what @vas3k can provide from the hq-project. Maybe there is already some usable data to get.

**Comment by yncyrydybyl** [comment]
The HQ-Parity Team can provide a widget which is doing this.
The widget needs to ask for permission via the [widget API](https://github.com/matrix-org/matrix-widget-api).

It should then get ```requestOpenIDConnectToken``` and validate at the matrixserver ```/_matrix/federation/v1/openid/userinfo```

**Comment by mordamax** [comment]
I think it'd be better to request Humaans to add these fields to a search index, instead of leveraging anyhow the admin bot

<img width="579" alt="Google Chrome 2024-07-26 18 13 23" src="https://github.com/user-attachments/assets/7773f46c-12d3-4ae9-bd9a-6b1dc57d3351">
