### ISSUE TITLE
Matrix: Set Reminders

### ISSUE THREAD

**Issue by mordamax** [paritytech/matrix-admin-bot#17]
There were several separate (but similar) requests:
> - Set reminders
> - Bots reminding around unanswered or unread questions
> - Bot for important emails being received. Bot reminder with check list (todo list) with deadlines

**Problem/Pain**: 
From the given requests, I can guess the main incentives are:
- to delay some action for later (either read message, or reply someone in forum, etc). Was thinking about having some context menu (right mouse click) on message
- to not forget to do something (like: set up a meeting with X, or send an 1). This could be custom - you ask bot to do X at Y time

**Solution**:
TBD

Existing similar tools:
- https://github.com/CubicrootXYZ/RemindMe
- https://github.com/anoadragon453/matrix-reminder-bot

**Comment by lovelaced** [comment]
People should just be instructed to use https://t2bot.io/reminderbot/

I'm going to close this.
