### ISSUE TITLE
Matrix: Google calendar integration

### ISSUE THREAD

**Issue by mordamax** [paritytech/matrix-admin-bot#19]
Similar to https://slack.com/app-pages/google-calendar, but not sure if we can & should implement everything from this
(like "changing status automatically" would be great, but matrix doesn't have statuses, only changing names)
Perhaps only calendar notifications?
The scope of this feature still TBD

**Comment by yncyrydybyl** [comment]
I think a integration of matrix room into scheduling meetings would be helpful.

Like jitsi is doing it.
[Jitsi Meet for Google Calendar - Google Workspace Marketplace](https://workspace.google.com/marketplace/app/jitsi_meet_for_google_calendar/421935948107)
[jitsi/jidesha: Issue #45](https://github.com/jitsi/jidesha/issues/45)
[GitHub - jitsi/calendar-addon: Calendar G Suite add-on](https://github.com/jitsi/calendar-addon)
