### ISSUE TITLE
Matrix: Change display name (or status) to OOO when on vacation (from bamboo)

### ISSUE THREAD

**Issue by mordamax** [paritytech/matrix-admin-bot#37]
This could be a bot which talks to the user and reminds you on something like display-name or status.
Or automatic change accordingly to Bamboo OOO status

> You can do it via the synapse admin API. You need the access_token of an admin account. Then you can do:
> 
> ```
> curl -X PUT --header 'Authorization: Bearer <access_token>' --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "displayname": "[ooo] Mak" }' 'https://matrix.parity.io/_synapse/admin/v2/users/@maksym:matrix.parity.io' -i
> ```

**Comment by yncyrydybyl** [comment]
I think this can work togeter with #32

**Comment by mordamax** [comment]
@yncyrydybyl i'm curious how technically it's possible?
afaik it's possible only if you provide the access_token of account? or any other ways?

There are couple of problems with tokens as I see - 
- token invalidates automatically if user logs out from session
- everyone needs to find/attach it explicitly, which naturally makes the feature Ignored, as pain in ass

**Comment by lovelaced** [comment]
We should absolutely not have users give access tokens for their accounts away.

**Comment by mutantcornholio** [comment]
Can `opstooling@parity.io` Bamboo account that we have for some reason help here?

**Comment by mordamax** [comment]
@mutantcornholio the question is who is able to change someone's name ? :) 
Per https://matrix.org/docs/api/#put-/_matrix/client/v3/profile/-userId-/displayname
> This API sets the given user's display name. You must have permission to set this user's display name, e.g. you need to have their access_token

if there's no secure/good way to share person's matrix `access_token` - my question is: what are the other ways to do this?

**Comment by yncyrydybyl** [comment]
You can do it via the synapse admin API. You need the access_token of an admin account. Then you can do:
```
curl -X PUT --header 'Authorization: Bearer <access_token>' --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ "displayname": "[ooo] Mak" }' 'https://matrix.parity.io/_synapse/admin/v2/users/@maksym:matrix.parity.io' -i
```

**Comment by gabreal** [comment]
imo a endpoint witch could be used to query absences could be useful and probably integrated into matrix as a widget or something somehow. i don't think it would be good to automate this for everyone directly, as it would reveal confidential information to externals in public rooms.

**Comment by lovelaced** [comment]
I'm going to close this as not planned because 1) what gabriel said, 2) we don't want to get in the business of changing anything about people's accounts with the admin api beyond password resets and explicit requests.

If teams want the absences bot that should do for the time being until statuses are finalized in element.
