### ISSUE TITLE
Tool needed: Matrix channel archiving bot

### ISSUE THREAD

**Issue by toholdaquill** [paritytech/matrix-admin-bot#9]
**Tell us your story**

Security team is proposing a new data deletion policy for our Matrix server. Matrix supports per-channel data deletion policies. Most of what happens on Matrix is ephemeral and should be deleted; some of it is important (for legal or other reasons) and should be archived.

What tools do we have available to archive Matrix threads that deserve archiving? Such a tool should be easy to use but not _too_ easy to use, as we don't want to wind up with everything being archived unencrypted on people's laptops.

**What tools have you already tried**

There does not appear to be a lot of publicly-available information on archiving Matrix channels.

**How bad is your pain?**

- [x] Itching from time to time
- [ ] Fairly intense. I would really like to solve it soon
- [ ] It often blocks me for a long time :'(

**Additional info**

This is a low-medium priority issue that needs to be addressed at some point in Q2 or Q3. (The answer might be: there is no such tool, and the effort required to build one is too high; but then again, perhaps a good solution exists or can be built with minimum effort? Unknown.)

**Comment by yncyrydybyl** [comment]
I just want to mention this little tool https://github.com/matrix-org/matrix-public-archive since it could be used for archiving public channels.

**Comment by vas3k** [comment]
@yncyrydybyl does it work for e2e encrypted rooms? Last time I checked I was convinced that most of the available libraries either do not work with it at all, or work poorly. I wrote my own (https://github.com/paritytech/opstooling/tree/master/bots/matrix-archivarius), but it works badly too and requires me to manually update the keys for the bot when a new room is created

**Comment by yncyrydybyl** [comment]
I havent tested it. But it says they use the [hydrogen client](https://github.com/vector-im/hydrogen-web). Which is capable of encryption.

**Comment by lovelaced** [comment]
I don't think this is really wanted anymore tbh. We want people to discuss on forums more so shouldn't need anything like this, if we need to publish history for something in particular we can do so.

**Comment by lovelaced** [comment]
You can export channels from the UI now and the main avenues of communication have moved to the polkadot forum and stackoverflow, there's really no use for this.
